version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-3.5
    container_name: postgis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgis_db
    ports:
      - "5432:5432"
    volumes:
      - histomap_pgdata:/var/lib/postgresql/data

  geoserver:
    image: docker.osgeo.org/geoserver:2.26.0
    container_name: geoserver
    volumes:
      - ./app_data/geoserver:/opt/geoserver_data
    ports:
      - "8080:8080"
    environment:
      - WEBAPP_CONTEXT=

volumes:
  histomap_pgdata:
