version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_USER: postgres  # Replace with your preferred username
      POSTGRES_PASSWORD: postgres  # Replace with your preferred password
      POSTGRES_DB: postgis_db  # Replace with your preferred database name
    ports:
      - "5432:5432"